Blog.create!(content:"Change your thoughts and you change your world.")
Blog.create!(content:"Those who realize their folly are not true fools.")
Blog.create!(content:"Life is too important to be taken seriously.")
Blog.create!(content:"Keep your eyes on the stars and your feet on the ground.")
Blog.create!(content:"It always seems impossible until it’s done.")
Blog.create!(content:"Difficult and meaningful will always bring more satisfaction than easy and meaningless.")
Blog.create!(content:"It is better to be hated for what you are than to be loved for what you are not.")
Blog.create!(content:"In the end, it’s not the years in your life that count. It’s the life in your years.")
Blog.create!(content:"Life is like playing a violin in public and learning the instrument as one goes on.")
Blog.create!(content:"It is better to be hated for what you are than to be loved for what you are not.")